//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZayavleniyIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        private static Entities _context;
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doljnosti> doljnosti { get; set; }
        public virtual DbSet<otzivi> otzivi { get; set; }
        public virtual DbSet<rehennie_zayvleniy> rehennie_zayvleniy { get; set; }
        public virtual DbSet<sotrudniki> sotrudniki { get; set; }
        public virtual DbSet<svoistva_zayvleni> svoistva_zayvleni { get; set; }
        public virtual DbSet<zayvitel> zayvitel { get; set; }
        public virtual DbSet<Zayvleniy> Zayvleniy { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
    }
}
