//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZayavleniyIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class otzivi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public otzivi()
        {
            this.rehennie_zayvleniy = new HashSet<rehennie_zayvleniy>();
        }
    
        public int id_отзыва { get; set; }
        public string дата { get; set; }
        public string состояние { get; set; }
        public int id_заявителя { get; set; }
    
        public virtual zayvitel zayvitel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rehennie_zayvleniy> rehennie_zayvleniy { get; set; }
    }
}
