//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZayavleniyIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class rehennie_zayvleniy
    {
        public int Номер_закрытия_заявления { get; set; }
        public string Дата { get; set; }
        public int id_свойств { get; set; }
        public int id_отзыва { get; set; }
    
        public virtual otzivi otzivi { get; set; }
        public virtual svoistva_zayvleni svoistva_zayvleni { get; set; }
    }
}
