//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZayavleniyIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class svoistva_zayvleni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public svoistva_zayvleni()
        {
            this.rehennie_zayvleniy = new HashSet<rehennie_zayvleniy>();
            this.Zayvleniy = new HashSet<Zayvleniy>();
        }
    
        public int id_свойств { get; set; }
        public string срок { get; set; }
        public int id_сотрудник { get; set; }
        public string вид { get; set; }
        public string статус { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rehennie_zayvleniy> rehennie_zayvleniy { get; set; }
        public virtual sotrudniki sotrudniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zayvleniy> Zayvleniy { get; set; }
    }
}
