//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZayavleniyIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int Номер_заявления { get; set; }
        public string Наименование { get; set; }
        public string срок { get; set; }
        public int id_сотрудника { get; set; }
        public string Фамилия { get; set; }
        public string статус { get; set; }
    }
}
